app = "hyroxscraper"
primary_region = "yyz"

[env]
  PORT = "10000"
  NODE_ENV = "production"

[build]
  image = "mcr.microsoft.com/playwright:v1.49.0-jammy"

[[services]]
  protocol = "tcp"
  internal_port = 10000

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
